FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    libsndfile1 \
    libasound2-dev \
    build-essential \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY vibez_api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY vibez_api/ .

ENV REDIS_HOST=redis
ENV REDIS_PORT=6379

EXPOSE 8010

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8010"]
