FROM oven/bun:1 AS builder

WORKDIR /app
COPY vibez-front/package.json vibez-front/bun.lockb* ./
RUN bun install --frozen-lockfile

COPY vibez-front/ .
RUN bun run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
